#!/bin/bash

t='Debug'
d='debug'
p='hamwalk'

fd=build/${d}

rm -rf ${fd}
mkdir -p ${fd}

cmake -DCMAKE_BUILD_TYPE=${t} -DCMAKE_MAKE_PROGRAM=ninja -G Ninja -S . -B ${fd}
cmake --build ${fd} --target ${p} -j14

cd ${fd}
./${p}
